/*
 * This file was generated by the mkbuiltins program.
 */

#define ALIASCMD (builtincmd + 3)
#define BREAKCMD (builtincmd + 4)
#define CDCMD (builtincmd + 5)
#define COMMANDCMD (builtincmd + 7)
#define DOTCMD (builtincmd + 0)
#define ECHOCMD (builtincmd + 9)
#define EVALCMD (builtincmd + 10)
#define EXECCMD (builtincmd + 11)
#define EXITCMD (builtincmd + 12)
#define EXPORTCMD (builtincmd + 13)
#define FALSECMD (builtincmd + 14)
#define GETOPTSCMD (builtincmd + 16)
#define HASHCMD (builtincmd + 17)
#define HISTCMD (builtincmd + 15)
#define JOBSCMD (builtincmd + 18)
#define KILLCMD (builtincmd + 19)
#define LOCALCMD (builtincmd + 20)
#define PRINTFCMD (builtincmd + 21)
#define PWDCMD (builtincmd + 22)
#define READCMD (builtincmd + 23)
#define RETURNCMD (builtincmd + 25)
#define SETCMD (builtincmd + 26)
#define SHIFTCMD (builtincmd + 27)
#define TESTCMD (builtincmd + 2)
#define TIMESCMD (builtincmd + 29)
#define TRAPCMD (builtincmd + 30)
#define TRUECMD (builtincmd + 1)
#define TYPECMD (builtincmd + 32)
#define UMASKCMD (builtincmd + 33)
#define UNALIASCMD (builtincmd + 34)
#define UNSETCMD (builtincmd + 35)
#define WAITCMD (builtincmd + 36)

#define NUMBUILTINS 37

#define BUILTIN_SPECIAL 0x1
#define BUILTIN_REGULAR 0x2
#define BUILTIN_ASSIGN 0x4

struct builtincmd {
	const char *name;
	int (*builtin)(int, char **);
	unsigned flags;
};

extern const struct builtincmd builtincmd[];
